import {
  ArticleComponent,
  ArticleEditorComponent,
  ArticleElementComponent,
  ArticleListComponent,
  ArticleViewComponent,
  CategoryArticlesListComponent,
  CategoryComponent,
  CategoryEditorComponent,
  ContentEditorComponent,
  ContentElementComponent,
  HeadingComponent,
  ImageComponent,
  ListItemComponent,
  ParagraphComponent,
} from '../../cms';

import {
  AsideNavComponent,
  AsideNavHeaderComponent,
  AsideNavItemComponent,
  CardBodyComponent,
  CardComponent,
  CardFooterComponent,
  CardImageComponent,
  CardTitleComponent,
  CodeBlockComponent,
  CollapsibleComponent,
  CollapsibleContentComponent,
  CollapsibleHeaderComponent,
  ColorPaletteComponent,
  DrawerComponent,
  ErrorComponent,
  FooterNavComponent,
  HamburgerComponent,
  ImageFormComponent,
  LinkFormComponent,
  MenuComponent,
  MetaFormComponent,
  ModalComponent,
  MultiSelectBoxComponent,
  PaginationComponent,
  SearchBoxComponent,
  SpinnerComponent,
  TabsComponent,
  ThemeComponent,
  ThemePickerComponent,
  ThemePreviewComponent,
  ToggleComponent,
  ToolbarComponent,
  TypographyComponent,
} from '../../common-ui';

import {
  LoginComponent,
  LoginStatusComponent,
} from '../../auth';


import {
  ComponentInfoComponent,
  ComponentPropsComponent,
  ComponentUsageComponent,
  ServiceInfoComponent,
  ServiceMethodComponent,
} from '../';

export const LibComponents = {
  // Common UI
  AsideNavComponent,
  AsideNavHeaderComponent,
  AsideNavItemComponent,
  CardBodyComponent,
  CardComponent,
  CardFooterComponent,
  CardImageComponent,
  CardTitleComponent,
  CodeBlockComponent,
  CollapsibleComponent,
  CollapsibleContentComponent,
  CollapsibleHeaderComponent,
  ColorPaletteComponent,
  DrawerComponent,
  ErrorComponent,
  FooterNavComponent,
  HamburgerComponent,
  ImageFormComponent,
  LinkFormComponent,
  MenuComponent,
  MetaFormComponent,
  ModalComponent,
  MultiSelectBoxComponent,
  PaginationComponent,
  SearchBoxComponent,
  SpinnerComponent,
  TabsComponent,
  ThemeComponent,
  ThemePickerComponent,
  ThemePreviewComponent,
  ToggleComponent,
  ToolbarComponent,
  TypographyComponent,

  // CMS
  ArticleComponent,
  ArticleEditorComponent,
  ArticleElementComponent,
  ArticleListComponent,
  ArticleViewComponent,
  CategoryArticlesListComponent,
  CategoryComponent,
  CategoryEditorComponent,
  ContentEditorComponent,
  ContentElementComponent,
  HeadingComponent,
  ImageComponent,
  ListItemComponent,
  ParagraphComponent,

  // Auth
  LoginComponent,
  LoginStatusComponent,

  // docs
  ComponentInfoComponent,
  ComponentPropsComponent,
  ComponentUsageComponent,
  ServiceInfoComponent,
  ServiceMethodComponent,
};
