import {
  ArticleComponent,
  ArticleEditorComponent,
  ArticleElementComponent,
  ArticleListComponent,
  ArticleViewComponent,
  CategoryArticlesListComponent,
  CategoryComponent,
  CategoryEditorComponent,
  ContentEditorComponent,
  ContentElementComponent,
  LeafElementComponent,
  OpenaiAutoArticlesComponent,
  ArticlesSlideshowComponent,
} from '../../cms';

import {
  AsideNavComponent,
  AsideNavHeaderComponent,
  AsideNavItemComponent,
  CardBodyComponent,
  CardComponent,
  CardFooterComponent,
  CardImageComponent,
  CardTitleComponent,
  CodeBlockComponent,
  CollapsibleComponent,
  CollapsibleContentComponent,
  CollapsibleHeaderComponent,
  ColorPaletteComponent,
  DrawerComponent,
  ErrorComponent,
  FooterNavComponent,
  HamburgerComponent,
  ImageFormComponent,
  LinkFormComponent,
  MenuComponent,
  MetaFormComponent,
  ModalComponent,
  MultiSelectBoxComponent,
  PaginationComponent,
  SearchBoxComponent,
  SpinnerComponent,
  TabsComponent,
  ThemeComponent,
  ThemePickerComponent,
  ThemePreviewComponent,
  ToggleComponent,
  ToolbarComponent,
  TypographyComponent,
  ImageBrowserComponent,
  FiltersComponent,
  ThemeFontResizerComponent,
  SitemapComponent,
  OpenaiFormComponent,
  OpenaiImageFormComponent,
  SlideshowComponent,
} from '../../common-ui';

import { LoginComponent, LoginStatusComponent } from '../../auth';

// import { ComponentInfoComponent } from '../component-info/component-info.component';
import { ComponentPropsComponent } from '../component-props/component-props.component';
// import { ComponentUsageComponent } from '../component-usage/component-usage.component';
import { ServiceInfoComponent } from '../service-info/service-info.component';
import { ServiceMethodComponent } from '../service-method/service-method.component';

export const LibComponents = {
  // Common UI
  AsideNavComponent,
  AsideNavHeaderComponent,
  AsideNavItemComponent,
  CardBodyComponent,
  CardComponent,
  CardFooterComponent,
  CardImageComponent,
  CardTitleComponent,
  CodeBlockComponent,
  CollapsibleComponent,
  CollapsibleContentComponent,
  CollapsibleHeaderComponent,
  ColorPaletteComponent,
  DrawerComponent,
  ErrorComponent,
  FooterNavComponent,
  HamburgerComponent,
  ImageFormComponent,
  LinkFormComponent,
  MenuComponent,
  MetaFormComponent,
  ModalComponent,
  MultiSelectBoxComponent,
  PaginationComponent,
  SearchBoxComponent,
  SpinnerComponent,
  TabsComponent,
  ThemeComponent,
  ThemePickerComponent,
  ThemePreviewComponent,
  ToggleComponent,
  ToolbarComponent,
  TypographyComponent,
  ImageBrowserComponent,
  FiltersComponent,
  ThemeFontResizerComponent,
  SitemapComponent,
  OpenaiFormComponent,
  OpenaiImageFormComponent,
  SlideshowComponent,

  // CMS
  ArticleComponent,
  ArticleEditorComponent,
  ArticleElementComponent,
  ArticleListComponent,
  ArticleViewComponent,
  CategoryArticlesListComponent,
  CategoryComponent,
  CategoryEditorComponent,
  ContentEditorComponent,
  ContentElementComponent,
  LeafElementComponent,
  OpenaiAutoArticlesComponent,
  ArticlesSlideshowComponent,

  // Auth
  LoginComponent,
  LoginStatusComponent,

  // docs
  // ComponentInfoComponent,
  ComponentPropsComponent,
  // ComponentUsageComponent,
  ServiceInfoComponent,
  ServiceMethodComponent,
};
